//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        public int FarmId { get; set; }
        public string FarmName { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
    }
}
